### ISSUE TITLE
Is R or R^2 drawn by `sm_statCorr()`?

### ISSUE THREAD

**Issue by gaospecial** [smin95/smplot2#1]
`sm_statCorr()` draw a text like "R = 0.23, p = 0.051", what is the meaning of R? Why not provide R^2 in the plot?

**Comment by smin95** [comment]
Hi Dr. Gao, thanks for your interest in the package.
R refers to the correlation coefficient. sm_statCorr() does not compute R^2. 
R can also be obtained using the base R function 'cor.test()' 
R^2 is not reported because the value is positive when correlations are negative or positive.
