### ISSUE TITLE
sm_bland_altman, different color for each first and second run

### ISSUE THREAD

**Issue by eliascrapa** [smin95/smplot2#3]
Hi, 

you made a really nice and easy to use package. Thank you very much. Is there a possibliity to color the rows differently?

Thanks

Tilo

**Comment by smin95** [comment]
I think a BA plot only plots points that summarise data from both sessions; it is essentially a scatterplot. So what I would do is, if the first session was blue and the second red, then the BA plot would have purple points as each point would represent both sessions. Thanks for your support.
