### ISSUE TITLE
Adding legend for regression lines in sm_statCorr

### ISSUE THREAD

**Issue by roberthardt** [smin95/smplot2#4]
Hi,

is there an easy way to add a separate legend for regression lines plotted by sm_statCorr? If I had created these lines by geom_smooth myself, I would know how to do this, but I cannot achieve it when using sm_statCorr.

Best
Robert

**Comment by smin95** [comment]
Hi Robert,

Thanks for your interest in the package. I don't think its possible with the function. What you can do is perhaps compute the best fit linear regression from the scatterpoints using lm(), and then use the slope to compute the line separately. Such an example can be found in section 9.1 of the package's homepage (https://www.smin95.com/dataviz/calculating-linear-slopes.html).

Best,
Sam
