### ISSUE TITLE
Adjusting position/distance of raincloud using sm_raincloud

### ISSUE THREAD

**Issue by ChlorisF** [smin95/smplot2#5]
Hi Sam,

Thanks for making this beautiful package! I'm drawing a raincloud plot that has three groups. I find that the clouds are rather thin and the distance in-between is a bit far. Is there a way to adjust the width of and/or distance between clouds?
![image](https://github.com/smin95/smplot2/assets/103331766/f5f27e20-4c50-4ca4-8902-64076949ef8c)

Many thanks,
Chloris

**Comment by smin95** [comment]
You can simply adjust the ratio of the figure. More examples are shown on my website: www.smin95.com/dataviz
Another way to do it is to change the sep_level of sm_raincloud

**Comment by smin95** [comment]
You can simply adjust the ratio of the figure. More examples are shown on my website: [www.smin95.com/dataviz](http://www.smin95.com/dataviz)
Another way to do it is to change the sep_level of sm_raincloud
