### ISSUE TITLE
Using Cronbach's alpha as method?

### ISSUE THREAD

**Issue by Beduiz** [smin95/smplot2#6]
Dear Dr Min,

Is it possible to in some way tweak the sm_statCorr() function to enable usage of correlation method Cronbach's alpha? It would be very useful!

Kind regards
Eric

**Comment by smin95** [comment]
Dear Eric,

Sorry for the late response and thanks for your interest. I do not think I will be able to get it done soon. You might have to rely on other R packages to do the computation. 

Best regards,
Sam
